/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projectgradle;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public int getSoma(int a, int b){
        return a+b;
    }

    public boolean getEven(int a){
        if(a % 2 == 0)
            return true;
        return false;
        }
    }

